export default {
   "root":"_vzuHsJS9u9E8WWkr48Jg",
   "byIds":{
      "_vzuHsJS9u9E8WWkr48Jg":{
         "id":"_vzuHsJS9u9E8WWkr48Jg",
         "type":"Canvas",
         "props":{
            "style":{
               "backgroundColor":"#f0eff1"
            }
         },
         "childIds":[
            "Qg79fzfB2QEKoXH2LR4wP",
            "v5-taJ46DSRspof62aGFM",
            "8jvhO1AEjcjMUTI2sXyfa"
         ],
         "parentId":null
      },
      "Qg79fzfB2QEKoXH2LR4wP":{
         "id":"Qg79fzfB2QEKoXH2LR4wP",
         "type":"Section",
         "props":{
            "style":{
               "width":"100%",
               "height":"450px",
               "backgroundColor":"#151019",
               "position":"absolute",
               "left":"0px",
               "top":"0px",
               "backgroundUrl":"./background.png",
               "backgroundPosition":"-490px -120px"
            }
         },
         "childIds":[
            "i7rYtsSgtw_btP7GYRMHj",
            "aEIxeD0SMFOBs_wu47zcd",
            "ium2hXKn1h_ULm7167eyu"
         ],
         "parentId":"_vzuHsJS9u9E8WWkr48Jg"
      },
      "i7rYtsSgtw_btP7GYRMHj":{
         "id":"i7rYtsSgtw_btP7GYRMHj",
         "type":"Text",
         "props":{
            "text":"Build UI",
            "style":{
               "color":"#ffffff",
               "fontSize":"60px",
               "fontFamily":"KoHo",
               "position":"absolute",
               "left":"9%",
               "top":"12%",
               "width":"232px",
               "height":"77px"
            }
         },
         "childIds":[
            
         ],
         "parentId":"Qg79fzfB2QEKoXH2LR4wP"
      },
      "ium2hXKn1h_ULm7167eyu":{
         "id":"ium2hXKn1h_ULm7167eyu",
         "type":"Text",
         "props":{
            "text":"Code your own page\neditors with React",
            "style":{
               "color":"#ffffff",
               "fontSize":"20px",
               "fontFamily":"KoHo",
               "position":"absolute",
               "left":"9.5%",
               "top":"28%",
               "width":"195px",
               "height":"66px"
            }
         },
         "childIds":[
            
         ],
         "parentId":"Qg79fzfB2QEKoXH2LR4wP"
      },
      "aEIxeD0SMFOBs_wu47zcd":{
         "id":"aEIxeD0SMFOBs_wu47zcd",
         "type":"Button",
         "props":{
            "text":"Visit Repository",
            "color":"primary",
            "variant":"contained",
            "style":{
               "position":"absolute",
               "left":"8%",
               "top":"65%",
               "width":"300px"
            }
         },
         "childIds":[
            
         ],
         "parentId":"Qg79fzfB2QEKoXH2LR4wP"
      },
      "v5-taJ46DSRspof62aGFM":{
         "id":"v5-taJ46DSRspof62aGFM",
         "type":"Section",
         "props":{
            "style":{
               "width":"100%",
               "height":"40px",
               "backgroundColor":"#1c1c28",
               "position":"absolute",
               "left":"0px",
               "top":"450px"
            }
         },
         "childIds":[
            
         ],
         "parentId":"_vzuHsJS9u9E8WWkr48Jg"
      },
      "8jvhO1AEjcjMUTI2sXyfa":{
         "id":"8jvhO1AEjcjMUTI2sXyfa",
         "type":"Section",
         "props":{
            "style":{
               "width":"100%",
               "height":"auto",
               "backgroundColor":"#262c3c",
               "position":"absolute",
               "left":"0px",
               "top":"490px",
               "display":"flex",
               "alignItems":"center",
               "justifyContent":"center"
            }
         },
         "childIds":[
            "6RFumRKml3Dg7OOJienzI"
         ],
         "parentId":"_vzuHsJS9u9E8WWkr48Jg"
      },
      "6RFumRKml3Dg7OOJienzI":{
         "id":"6RFumRKml3Dg7OOJienzI",
         "type":"Section",
         "props":{
            "style":{
               "width":"80%",
               "height":"80%",
               "backgroundColor":"#262c3c",
               "position":"absolute",
               "left":"10%",
               "top":"10%"
            }
         },
         "childIds":[
            "BAB8Ix0XIQHxWkyK5t3a1"
         ],
         "parentId":"8jvhO1AEjcjMUTI2sXyfa"
      },
      "BAB8Ix0XIQHxWkyK5t3a1":{
         "id":"BAB8Ix0XIQHxWkyK5t3a1",
         "type":"Grid",
         "props":{
            "container":true,
            "item":false,
            "xs":12,
            "style":{
               "position":"absolute",
               "left":"117.9375px",
               "top":"83.203125px",
               "height":"100%",
               "width":"100%",
               "backgroundColor":"#b5c2c4"
            }
         },
         "childIds":[
            "L2j_jOFvZdsEfLCdx0S5i",
            "s88uoy3Q3kzAZfxpNAnU3",
            "x_YTI16dNpV5uQYvLbAul"
         ],
         "parentId":"6RFumRKml3Dg7OOJienzI"
      },
      "L2j_jOFvZdsEfLCdx0S5i":{
         "id":"L2j_jOFvZdsEfLCdx0S5i",
         "type":"Grid",
         "props":{
            "container":true,
            "item":true,
            "xs":12,
            "style":{
               "position":"absolute",
               "left":"134.9375px",
               "top":"95.203125px",
               "height":"400px",
               "width":"100%",
               "xs":{
                  "height":"250px"
               },
               "md":{
                  "height":"400px"
               }
            },
            "md":4
         },
         "childIds":[
            "MRgnYBzWun_3tDdaMoA1b"
         ],
         "parentId":"BAB8Ix0XIQHxWkyK5t3a1"
      },
      "MRgnYBzWun_3tDdaMoA1b":{
         "id":"MRgnYBzWun_3tDdaMoA1b",
         "type":"Section",
         "props":{
            "style":{
               "width":"100%",
               "height":"100%",
               "backgroundColor":"#262c3c",
               "position":"absolute",
               "left":"",
               "top":"",
               "display":"flex",
               "alignItems":"center",
               "justifyContent":"center",
               "flexDirection":"column"
            }
         },
         "childIds":[
            "NThMZ8xq6Djly12thlCKf",
            "M7xUgnRFxP9YD5KJRuzsL"
         ],
         "parentId":"L2j_jOFvZdsEfLCdx0S5i"
      },
      "s88uoy3Q3kzAZfxpNAnU3":{
         "id":"s88uoy3Q3kzAZfxpNAnU3",
         "type":"Grid",
         "props":{
            "container":true,
            "item":true,
            "xs":12,
            "style":{
               "height":"400px",
               "width":"100%",
               "xs":{
                  "height":"250px"
               },
               "md":{
                  "height":"400px"
               }
            },
            "md":4
         },
         "childIds":[
            "bQA9V-eyfhDPfyhMKzHzi"
         ],
         "parentId":"BAB8Ix0XIQHxWkyK5t3a1"
      },
      "bQA9V-eyfhDPfyhMKzHzi":{
         "id":"bQA9V-eyfhDPfyhMKzHzi",
         "type":"Section",
         "props":{
            "style":{
               "width":"100%",
               "height":"100%",
               "backgroundColor":"#262c3c",
               "top":"",
               "display":"flex",
               "alignItems":"center",
               "justifyContent":"center",
               "flexDirection":"column"
            }
         },
         "childIds":[
            "JTJifHwJxTpELelynpXuX",
            "fSsnUq4w7nqHw_sYg5k1j"
         ],
         "parentId":"s88uoy3Q3kzAZfxpNAnU3"
      },
      "x_YTI16dNpV5uQYvLbAul":{
         "id":"x_YTI16dNpV5uQYvLbAul",
         "type":"Grid",
         "props":{
            "container":true,
            "item":true,
            "xs":12,
            "style":{
               "height":"400px",
               "backgroundColor":"#b5c2c4",
               "width":"100%",
               "xs":{
                  "height":"250px"
               },
               "md":{
                  "height":"400px"
               }
            },
            "md":4
         },
         "childIds":[
            "b5H9vGCwc8GAJFiaq85du"
         ],
         "parentId":"BAB8Ix0XIQHxWkyK5t3a1"
      },
      "b5H9vGCwc8GAJFiaq85du":{
         "id":"b5H9vGCwc8GAJFiaq85du",
         "type":"Section",
         "props":{
            "style":{
               "width":"100%",
               "height":"100%",
               "backgroundColor":"#262c3c",
               "display":"flex",
               "flexDirection":"column",
               "alignItems":"center",
               "justifyContent":"center"
            }
         },
         "childIds":[
            "IfMQyGmK-okSCrb2fQWRh",
            "ICLBl2JAtm_WNmYa2iGmM"
         ],
         "parentId":"x_YTI16dNpV5uQYvLbAul"
      },
      "NThMZ8xq6Djly12thlCKf":{
         "id":"NThMZ8xq6Djly12thlCKf",
         "type":"Image",
         "props":{
            "src":"./html_tags.svg",
            "style":{
               "width":"200px",
               "height":"172px",
               "position":"absolute",
               "left":"",
               "top":""
            }
         },
         "childIds":[
            
         ],
         "parentId":"MRgnYBzWun_3tDdaMoA1b"
      },
      "M7xUgnRFxP9YD5KJRuzsL":{
         "id":"M7xUgnRFxP9YD5KJRuzsL",
         "type":"Text",
         "props":{
            "text":"Intuitive API",
            "style":{
               "color":"#ffffff",
               "fontSize":"30px",
               "fontFamily":"KoHo",
               "position":"absolute",
               "left":"",
               "top":"",
               "textAlign":"center",
               "width":"100%",
               "height":"45px"
            }
         },
         "childIds":[
            
         ],
         "parentId":"MRgnYBzWun_3tDdaMoA1b"
      },
      "JTJifHwJxTpELelynpXuX":{
         "id":"JTJifHwJxTpELelynpXuX",
         "type":"Image",
         "props":{
            "src":"./html_tags.svg",
            "style":{
               "width":200,
               "height":172,
               "position":"absolute",
               "left":"",
               "top":""
            }
         },
         "childIds":[
            
         ],
         "parentId":"bQA9V-eyfhDPfyhMKzHzi"
      },
      "fSsnUq4w7nqHw_sYg5k1j":{
         "id":"fSsnUq4w7nqHw_sYg5k1j",
         "type":"Text",
         "props":{
            "text":"Declarative",
            "style":{
               "color":"#ffffff",
               "fontSize":"30px",
               "fontFamily":"KoHo",
               "position":"absolute",
               "left":"",
               "top":"",
               "textAlign":"center",
               "width":"100%",
               "height":"45px"
            }
         },
         "childIds":[
            
         ],
         "parentId":"bQA9V-eyfhDPfyhMKzHzi"
      },
      "IfMQyGmK-okSCrb2fQWRh":{
         "id":"IfMQyGmK-okSCrb2fQWRh",
         "type":"Image",
         "props":{
            "src":"./html_tags.svg",
            "style":{
               "width":200,
               "height":172,
               "position":"absolute",
               "left":"",
               "top":""
            }
         },
         "childIds":[
            
         ],
         "parentId":"b5H9vGCwc8GAJFiaq85du"
      },
      "ICLBl2JAtm_WNmYa2iGmM":{
         "id":"ICLBl2JAtm_WNmYa2iGmM",
         "type":"Text",
         "props":{
            "text":"Extensible",
            "style":{
               "color":"#ffffff",
               "fontSize":"30px",
               "fontFamily":"KoHo",
               "position":"absolute",
               "left":"",
               "top":"",
               "textAlign":"center",
               "height":"45px",
               "width":"100%"
            }
         },
         "childIds":[
            
         ],
         "parentId":"b5H9vGCwc8GAJFiaq85du"
      }
   },
   "meta":{
      "_vzuHsJS9u9E8WWkr48Jg":{
         "id":"_vzuHsJS9u9E8WWkr48Jg",
         "layer_hover":null
      },
      "Qg79fzfB2QEKoXH2LR4wP":{
         "id":"Qg79fzfB2QEKoXH2LR4wP",
         "fixed":true
      },
      "i7rYtsSgtw_btP7GYRMHj":{
         "id":"i7rYtsSgtw_btP7GYRMHj"
      },
      "ium2hXKn1h_ULm7167eyu":{
         "id":"ium2hXKn1h_ULm7167eyu"
      },
      "aEIxeD0SMFOBs_wu47zcd":{
         "id":"aEIxeD0SMFOBs_wu47zcd"
      },
      "v5-taJ46DSRspof62aGFM":{
         "id":"v5-taJ46DSRspof62aGFM",
         "fixed":true
      },
      "8jvhO1AEjcjMUTI2sXyfa":{
         "id":"8jvhO1AEjcjMUTI2sXyfa",
         "layer_hover":null,
         "fixed":true
      },
      "6RFumRKml3Dg7OOJienzI":{
         "id":"6RFumRKml3Dg7OOJienzI",
         "layer_hover":null,
         "fixed":true
      },
      "BAB8Ix0XIQHxWkyK5t3a1":{
         "id":"BAB8Ix0XIQHxWkyK5t3a1",
         "layer_hover":null,
         "fixed":true
      },
      "L2j_jOFvZdsEfLCdx0S5i":{
         "id":"L2j_jOFvZdsEfLCdx0S5i",
         "layer_hover":null,
         "fixed":true
      },
      "MRgnYBzWun_3tDdaMoA1b":{
         "id":"MRgnYBzWun_3tDdaMoA1b",
         "fixed":true
      },
      "s88uoy3Q3kzAZfxpNAnU3":{
         "id":"s88uoy3Q3kzAZfxpNAnU3",
         "layer_hover":null,
         "fixed":true
      },
      "bQA9V-eyfhDPfyhMKzHzi":{
         "id":"bQA9V-eyfhDPfyhMKzHzi",
         "fixed":true
      },
      "x_YTI16dNpV5uQYvLbAul":{
         "id":"x_YTI16dNpV5uQYvLbAul",
         "fixed":true
      },
      "b5H9vGCwc8GAJFiaq85du":{
         "id":"b5H9vGCwc8GAJFiaq85du",
         "fixed":true
      },
      "NThMZ8xq6Djly12thlCKf":{
         "id":"NThMZ8xq6Djly12thlCKf"
      },
      "M7xUgnRFxP9YD5KJRuzsL":{
         "id":"M7xUgnRFxP9YD5KJRuzsL",
         "layer_hover":null
      },
      "JTJifHwJxTpELelynpXuX":{
         "id":"JTJifHwJxTpELelynpXuX"
      },
      "fSsnUq4w7nqHw_sYg5k1j":{
         "id":"fSsnUq4w7nqHw_sYg5k1j"
      },
      "IfMQyGmK-okSCrb2fQWRh":{
         "id":"IfMQyGmK-okSCrb2fQWRh"
      },
      "ICLBl2JAtm_WNmYa2iGmM":{
         "id":"ICLBl2JAtm_WNmYa2iGmM"
      }
   },
   "index":{
      "panel":"Qg79fzfB2QEKoXH2LR4wP"
   },
   "index_list":{
      "selected":[
         
      ]
   }
}