import createVersionedSlice from '../history/wrappers/createVersionedSlice';
import {branch, normalizeBranch} from '../utils/tree';
import {
    createNode as createNodeReducer,
    deleteNode as deleteNodeReducer,
    intershiftNode as intershiftNodeReducer,
    moveNode as moveNodeReducer,
    replaceTree as replaceTreeReducer,
    updateNode as updateNodeReducer,
    rewriteNode as rewriteNodeReducer,
    createMeta as createMetaReducer,
    deleteMeta as deleteMetaReducer,
    updateMeta as updateMetaReducer,
    createIndex as createIndexReducer,
    deleteIndex as deleteIndexReducer,
    addIndex as addIndexReducer,
    removeIndex as removeIndexReducer,
    toggleIndex as toggleIndexReducer,
    clearIndex as clearIndexReducer,
    addListIndex as addListIndexReducer,
    removeListIndex as removeListIndexReducer,
    toggleListIndex as toggleListIndexReducer,
    clearListIndex as clearListIndexReducer,
} from '../reducers/tree';

const reducers = {
    createNode: createNodeReducer,
    deleteNode: deleteNodeReducer,
    intershiftNode: intershiftNodeReducer,
    moveNode: moveNodeReducer,
    replaceTree: replaceTreeReducer,
    rewriteNode: rewriteNodeReducer,
    updateNode: updateNodeReducer,
    createMeta: createMetaReducer,
    deleteMeta: deleteMetaReducer,
    updateMeta: updateMetaReducer,
    createIndex: createIndexReducer,
    deleteIndex: deleteIndexReducer,
    addIndex: addIndexReducer,
    removeIndex: removeIndexReducer,
    toggleIndex: toggleIndexReducer,
    clearIndex: clearIndexReducer,
    addListIndex: addListIndexReducer,
    removeListIndex: removeListIndexReducer,
    toggleListIndex: toggleListIndexReducer,
    clearListIndex: clearListIndexReducer,
}

const tree = createVersionedSlice({
    name: 'tree',
    reducers: reducers,
});

const batched = tree.extraActions.batched;
const unbatched = tree.extraActions.unbatched;
const unrecorded = tree.extraActions.unrecorded;

const actions = tree.actions;

const {
    createNode: createNodeBatched,
    deleteNode: deleteNodeBatched,
    intershiftNode: intershiftNodeBatched,
    moveNode: moveNodeBatched,
    updateNode: updateNodeBatched,
    rewriteNode: rewriteNodeBatched,
    createMeta: createMetaBatched,
    deleteMeta: deleteMetaBatched,
    updateMeta: updateMetaBatched,
    createIndex: createIndexBatched,
    deleteIndex: deleteIndexBatched,
    addIndex: addIndexBatched,
    removeIndex: removeIndexBatched,
    toggleIndex: toggleIndexBatched,
    clearIndex: clearIndexBatched,
    addListIndex: addListIndexBatched,
    removeListIndex: removeListIndexBatched,
    toggleListIndex: toggleListIndexBatched,
    clearListIndex: clearListIndexBatched,
    replaceTree: replaceTreeBatched,
} = batched;

const {
    createNode: createNodeUnbatched,
    deleteNode: deleteNodeUnbatched,
    intershiftNode: intershiftNodeUnbatched,
    moveNode: moveNodeUnbatched,
    updateNode: updateNodeUnbatched,
    rewriteNode: rewriteNodeUnbatched,
    createMeta: createMetaUnbatched,
    deleteMeta: deleteMetaUnbatched,
    updateMeta: updateMetaUnbatched,
    createIndex: createIndexUnbatched,
    deleteIndex: deleteIndexUnbatched,
    addIndex: addIndexUnbatched,
    removeIndex: removeIndexUnbatched,
    toggleIndex: toggleIndexUnbatched,
    clearIndex: clearIndexUnbatched,
    addListIndex: addListIndexUnbatched,
    removeListIndex: removeListIndexUnbatched,
    toggleListIndex: toggleListIndexUnbatched,
    clearListIndex: clearListIndexUnbatched,
    replaceTree: replaceTreeUnbatched,
} = unbatched;

const {
    createNode: createNodeUnrecorded,
    deleteNode: deleteNodeUnrecorded,
    intershiftNode: intershiftNodeUnrecorded,
    moveNode: moveNodeUnrecorded,
    updateNode: updateNodeUnrecorded,
    rewriteNode: rewriteNodeUnrecorded,
    createMeta: createMetaUnrecorded,
    deleteMeta: deleteMetaUnrecorded,
    updateMeta: updateMetaUnrecorded,
    createIndex: createIndexUnrecorded,
    deleteIndex: deleteIndexUnrecorded,
    addIndex: addIndexUnrecorded,
    removeIndex: removeIndexUnrecorded,
    toggleIndex: toggleIndexUnrecorded,
    clearIndex: clearIndexUnrecorded,
    addListIndex: addListIndexUnrecorded,
    removeListIndex: removeListIndexUnrecorded,
    toggleListIndex: toggleListIndexUnrecorded,
    clearListIndex: clearListIndexUnrecorded,
    replaceTree: replaceTreeUnrecorded,
} = unrecorded;

const {
    undoHistory,
    redoHistory,
    restartHistory,
    commitHistory,
    configureHistory,
    configureBatchHistory,
} = actions;

export default tree;

export {
    // Batched actions
    createNodeBatched,
    deleteNodeBatched,
    intershiftNodeBatched,
    moveNodeBatched,
    updateNodeBatched,
    rewriteNodeBatched,
    createMetaBatched,
    deleteMetaBatched,
    updateMetaBatched,
    createIndexBatched,
    deleteIndexBatched,
    addIndexBatched,
    removeIndexBatched,
    toggleIndexBatched,
    clearIndexBatched,
    addListIndexBatched,
    removeListIndexBatched,
    toggleListIndexBatched,
    clearListIndexBatched,
    replaceTreeBatched,
    // Unbatched actions
    createNodeUnbatched,
    deleteNodeUnbatched,
    intershiftNodeUnbatched,
    moveNodeUnbatched,
    updateNodeUnbatched,
    rewriteNodeUnbatched,
    createMetaUnbatched,
    deleteMetaUnbatched,
    updateMetaUnbatched,
    createIndexUnbatched,
    deleteIndexUnbatched,
    addIndexUnbatched,
    removeIndexUnbatched,
    toggleIndexUnbatched,
    clearIndexUnbatched,
    addListIndexUnbatched,
    removeListIndexUnbatched,
    toggleListIndexUnbatched,
    clearListIndexUnbatched,
    replaceTreeUnbatched,
    // Unrecorded actions
    createNodeUnrecorded,
    deleteNodeUnrecorded,
    intershiftNodeUnrecorded,
    moveNodeUnrecorded,
    updateNodeUnrecorded,
    rewriteNodeUnrecorded,
    createMetaUnrecorded,
    deleteMetaUnrecorded,
    updateMetaUnrecorded,
    createIndexUnrecorded,
    deleteIndexUnrecorded,
    addIndexUnrecorded,
    removeIndexUnrecorded,
    toggleIndexUnrecorded,
    clearIndexUnrecorded,
    addListIndexUnrecorded,
    removeListIndexUnrecorded,
    toggleListIndexUnrecorded,
    clearListIndexUnrecorded,
    replaceTreeUnrecorded,
    // History actions
    undoHistory,
    redoHistory,
    restartHistory,
    commitHistory,
    configureHistory,
    configureBatchHistory,
};